### ISSUE TITLE
Storage persisting on refresh

### ISSUE THREAD

**Issue by dr3** [n7olkachev/react-native-sync-storage#1]
.

**Comment by n7olkachev** [comment]
It has background syncing with `AsyncStorage` when you change it. Actually, source code is pretty small and easy so you can check it out.

**Comment by drewmcmillan** [comment]
Yeah, Im just not sure why it doesn't seem to save it on reload. It uses `AsyncStorage` but unlike plain `AsyncStorage` it doesn't persist. Looking at the code I cant really see why

**Comment by n7olkachev** [comment]
Are you sure you are making `await storage.init`? I don't have any problems with reloading.

**Comment by drewmcmillan** [comment]
I used `storage.set('property', 2333)`, ran it, and then deleted the line and wrote this

`class Main extends Component {      componentDidMount() {         this._loadInitialState().done();     }      _loadInitialState = async () => {         await storage.init;     };       render() {         AsyncStorage.getItem('state').then((token) => {             if(token != undefined){                 console.log(JSON.parse(token)); //RETURNS Object {property: 2333}             }         });          console.log(storage.get('property')); // RETURNS UNDEFINED        return(         <View>          </View>       )     } }
`

**Comment by drewmcmillan** [comment]
I used `storage.set('property', 2333)`, ran it, and then deleted the line and wrote this

`class Main extends Component {      

componentDidMount() {         
this._loadInitialState().done();     
}      

_loadInitialState = async () => {         await storage.init;     };       

render() {         

AsyncStorage.getItem('state').then((token) => {             
  if(token != undefined){                 
        console.log(JSON.parse(token)); //RETURNS Object {property: 2333}             
  }         
});          

console.log(storage.get('property')); // RETURNS UNDEFINED        

return(<View>          </View>)     
} 


}
`

**Comment by n7olkachev** [comment]
Because you didn't actually await for init. Render method will be executed before _loadInitialData completes, check it.

**Comment by drewmcmillan** [comment]
How do you avoid that? :/

**Comment by n7olkachev** [comment]
Add loaded state to your component default to false and change it to true after init. Then in render method return spinner or simple null if loaded is false and return your view if loaded is true.
